services:
  - type: web
    name: nexo-estoque-web
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
